language: node_js

cache:
  directories:
    - $HOME/.npm

node_js:
  - '10'
  - '12'
  - '14'

env:
  - SERVERLESS_VERSION=latest COV_PUB=true


before_install:
  - npm i -g npm@6

install:
  - travis_retry npm install
  - travis_retry npm install --no-save --ignore-scripts `npx npm-get-version serverless@$SERVERLESS_VERSION`

script:
  - npm run lint
  - npm test

after_success: test -z "$COV_PUB" || npm run coverage