service: serverless-typescript-complete-sample

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.REGIONS.${self:provider.stage}}
  deploymentBucket:
    name: ${self:custom.DEPLOYMENT_FOLDER.${self:provider.stage}}
  stackTags:
    projectName: typescript-sample-project
  environment: ${file(ymls/environment.yml)}
  vpc:
    securityGroupIds: ${self:custom.SECURITY_GROUP_IDS.${self:provider.stage}}
    subnetIds: ${self:custom.SUBNETS_IDS.${self:provider.stage}}
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

functions: ${file(ymls/functions.yml)}
custom: ${file(ymls/custom.yml)}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-log-retention
  - serverless-iam-roles-per-function
  - serverless-plugin-canary-deployments

package:
  exclude:
    - node_modules/serverless-**
    - coverage/**
    - test/**
    - .nyc_output/**
    - .gitignore
    - package-lock.json
    - README.md
    - docs/**
    - .vscode/**
    - ymls/**
    - .eslintrc.js
    - .eslintignore
    - .editorconfig
